(load "proj.lisp")
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "------Procura-pp-----~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(time (executa-jogadas (problema-estado-inicial p1) (procura-pp p1)))
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "------Procura-A*-----~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(time (executa-jogadas (problema-estado-inicial p1) (procura-A* p1 #'(lambda (x) 0))))
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "-----Procura-best----~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(format t "---------------------~c" #\linefeed)
(time (executa-jogadas (problema-estado-inicial p1) (procura-best (tr-tab (estado-tabuleiro (problema-estado-inicial p1))) (estado-pecas-por-colocar (problema-estado-inicial p1)))))