(load "proj.lisp")
(defconstant peca-i0 (make-array (list 4 1) :initial-element T))
(defvar accao (cria-accao 0 peca-i0))
(defvar accao1 (cria-accao 1 peca-i0))
(defvar accao2 (cria-accao 3 peca-i0))
(format T "~d ~c" accao #\linefeed)
(format T "~d ~c" (accao-coluna accao) #\linefeed)
(format T "~d ~c" (accao-peca accao) #\linefeed)
(format T "~d ~c" accao1 #\linefeed)
(format T "~d ~c" (accao-coluna accao1) #\linefeed)
(format T "~d ~c" (accao-peca accao1) #\linefeed)
(format T "~d ~c" accao2 #\linefeed)
(format T "~d ~c" (accao-coluna accao2) #\linefeed)
(format T "~d ~c" (accao-peca accao2) #\linefeed)